In [1]:
import numpy as np
import pandas as pd

C:\Users\Misha\AppData\Local\Temp\ipykernel_10984\1662815981.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

# Task 0
Read the dataset from csv file & perform data cleaning - remove all rows, which contains `?` in some columns.
Also check for data correctness (salary & salary $K).

In [15]:
data = pd.read_csv('../data/adult.csv')

data_clean = data.replace("?", pd.NA).dropna()

if "salary" in data_clean.columns and "salary$K" in data_clean.columns:
    data_clean["salary$K_calc"] = data_clean["salary"] / 1000

    incorrect_rows = data_clean[
        data_clean["salary$K_calc"] != data_clean["salary$K"]
    ]

    print("Number of incorrect salary rows:", len(incorrect_rows))
else:
    print("Salary columns not found in dataset.")
  
data_clean = data_clean.drop(columns=["salary$K_calc"], errors="ignore")

data.info()

data.head()

Salary columns not found in dataset.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      32561 non-null  int64
 1   age             32561 non-null  int64
 2   workclass       32561 non-null  object
 3   education       32561 non-null  object
 4   marital-status  32561 non-null  object
 5   occupation      32561 non-null  object
 6   relationship    32561 non-null  object
 7   race            32561 non-null  object
 8   sex             32561 non-null  object
 9   hours-per-week  32561 non-null  int64
 10  native-country  32561 non-null  object
 11  salary          32561 non-null  object
 12  salary K$       32561 non-null  int64
dtypes: int64(4), object(9)
memory usage: 3.2+ MB

,Unnamed: 0,age,workclass,education,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,salary,salary K$
0,0,39,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,40,United-States,<=50K,39
1,1,50,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,13,United-States,<=50K,35
2,2,38,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,40,United-States,<=50K,27
3,3,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,40,United-States,<=50K,43
4,4,28,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,40,Cuba,<=50K,25

# Task 1
Print the count of men and women in the dataset.

In [7]:
data["sex"].value_counts()

sex
Male      21790
Female    10771
Name: count, dtype: int64

# Task 2
Find the average age of men in dataset

In [8]:
data[data["sex"] == "Male"]["age"].mean()

39.43354749885268

# Task 3
Get the percentage of people from Poland (native-country)

In [12]:
len(data[data["native-country"] == "Poland"]) * 100 / len(data)

0.18426952489174164

# Task 4
Get the mean and standard deviation of the age for people who earn > 50K per year. After this, get it for those who earn <= 50K.

In [17]:
data[data["salary K$"] > 50]["age"].mean()
data[data["salary K$"] > 50]["age"].std()

data[data["salary K$"] <= 50]["age"].mean()
data[data["salary K$"] <= 50]["age"].std()

14.02008849082488

# Task 5
Check, if there are some people without higher education (education: Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters, Doctorate), but with > 50K salary

In [19]:
higher_edu = [
    "Bachelors",
    "Prof-school",
    "Assoc-acdm",
    "Assoc-voc",
    "Masters",
    "Doctorate"
]

# Filter rows: NOT in higher_edu AND salary > 50K
result = data[
    (~data["education"].isin(higher_edu)) &
    (data["salary"] == ">50K")
]

result

,Unnamed: 0,age,workclass,education,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,salary,salary K$
7,7,52,Self-emp-not-inc,HS-grad,Married-civ-spouse,Exec-managerial,Husband,White,Male,45,United-States,>50K,307
10,10,37,Private,Some-college,Married-civ-spouse,Exec-managerial,Husband,Black,Male,80,United-States,>50K,116
27,27,54,?,Some-college,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,60,South,>50K,275
38,38,31,Private,Some-college,Married-civ-spouse,Sales,Husband,White,Male,38,?,>50K,166
55,55,43,Private,Some-college,Married-civ-spouse,Tech-support,Husband,White,Male,40,United-States,>50K,341
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32510,32510,39,Private,HS-grad,Married-civ-spouse,Prof-specialty,Husband,White,Male,45,?,>50K,212
32518,32518,57,Local-gov,HS-grad,Married-civ-spouse,Craft-repair,Husband,White,Male,40,United-States,>50K,116
32519,32519,46,Private,Some-college,Married-civ-spouse,Exec-managerial,Husband,White,Male,48,United-States,>50K,239
32557,32557,40,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,40,United-States,>50K,173
32560,32560,52,Self-emp-inc,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,40,United-States,>50K,243

# Task 6
Get the statistics of age for each type of education. Use `groupby` and `describe` for this.

In [20]:
data.groupby("education")["age"].describe()

                count       mean        std   min    25%   50%   75%   max
education
10th            933.0  37.429796  16.720713  17.0  22.00  34.0  52.0  90.0
11th           1175.0  32.355745  15.545485  17.0  18.00  28.0  43.0  90.0
12th            433.0  32.000000  14.334625  17.0  19.00  28.0  41.0  79.0
1st-4th         168.0  46.142857  15.615625  19.0  33.00  46.0  57.0  90.0
5th-6th         333.0  42.885886  15.557285  17.0  29.00  42.0  54.0  84.0
7th-8th         646.0  48.445820  16.092350  17.0  34.25  50.0  61.0  90.0
9th             514.0  41.060311  15.946862  17.0  28.00  39.0  54.0  90.0
Assoc-acdm     1067.0  37.381443  11.095177  19.0  29.00  36.0  44.0  90.0
Assoc-voc      1382.0  38.553546  11.631300  19.0  30.00  37.0  46.0  84.0
Bachelors      5355.0  38.904949  11.912210  19.0  29.00  37.0  46.0  90.0
Doctorate       413.0  47.702179  11.784716  24.0  39.00  47.0  55.0  80.0
HS-grad       10501.0  38.974479  13.541524  17.0  28.00  37.0  48.0  90.0
Masters        1723.0  44.049913  11.068935  18.0  36.00  43.0  51.0  90.0
Preschool        51.0  42.764706  15.126914  19.0  31.00  41.0  53.5  75.0
Prof-school     576.0  44.746528  11.962477  25.0  36.00  43.0  51.0  90.0
Some-college   7291.0  35.756275  13.474051  17.0  24.00  34.0  45.0  90.0

# Task 7
Compare the married and non-married men salaries. Who earns more? (>50K or <=50K)
Married men are those, whom `marital-status` starts with "Married". Others are not.

In [21]:
men = data[data["sex"] == "Male"]
married_mask = men["marital-status"].str.startswith("Married")

married_men = men[married_mask]
non_married_men = men[~married_mask]

married_salary = married_men["salary"].value_counts()
non_married_salary = non_married_men["salary"].value_counts()

married_salary, non_married_salary

(salary
 <=50K    7576
 >50K     5965
 Name: count, dtype: int64,
 salary
 <=50K    7552
 >50K      697
 Name: count, dtype: int64)

# Task 8
Get the max hours per week some person works. How many people works the same amount of hours per week?

In [22]:
max_hours = data["hours-per-week"].max()
count_max_hours = (data["hours-per-week"] == max_hours).sum()

max_hours, count_max_hours

(99, 85)

# Task 9
Analyze the correlation between data in dataset. Understand connected fields in it and print highlight thier connection.

NameError: name 'LabelEncoder' is not defined