In [1]:
import numpy as np
import pandas as pd

C:\Users\Misha\AppData\Local\Temp\ipykernel_10984\1662815981.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

# Task 0
Read the dataset from csv file & perform data cleaning - remove all rows, which contains `?` in some columns.
Also check for data correctness (salary & salary $K).

In [38]:
data = pd.read_csv('../data/adult.csv')

data_clean = data.replace("?", pd.NA).dropna()

if "salary" in data_clean.columns and "salary$K" in data_clean.columns:
    data_clean["salary$K_calc"] = data_clean["salary"] / 1000

    incorrect_rows = data_clean[
        data_clean["salary$K_calc"] != data_clean["salary$K"]
    ]

    print("Number of incorrect salary rows:", len(incorrect_rows))
else:
    print("Salary columns not found in dataset.")
  
data_clean = data_clean.drop(columns=["salary$K_calc"], errors="ignore")

data_clean.info()

data_clean.head()

Salary columns not found in dataset.
<class 'pandas.core.frame.DataFrame'>
Index: 30162 entries, 0 to 32560
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      30162 non-null  int64
 1   age             30162 non-null  int64
 2   workclass       30162 non-null  object
 3   education       30162 non-null  object
 4   marital-status  30162 non-null  object
 5   occupation      30162 non-null  object
 6   relationship    30162 non-null  object
 7   race            30162 non-null  object
 8   sex             30162 non-null  object
 9   hours-per-week  30162 non-null  int64
 10  native-country  30162 non-null  object
 11  salary          30162 non-null  object
 12  salary K$       30162 non-null  int64
dtypes: int64(4), object(9)
memory usage: 3.2+ MB

,Unnamed: 0,age,workclass,education,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,salary,salary K$
0,0,39,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,40,United-States,<=50K,39
1,1,50,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,13,United-States,<=50K,35
2,2,38,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,40,United-States,<=50K,27
3,3,53,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,40,United-States,<=50K,43
4,4,28,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,40,Cuba,<=50K,25

# Task 1
Print the count of men and women in the dataset.

In [26]:
data_clean["sex"].value_counts()

sex
Male      20380
Female     9782
Name: count, dtype: int64

# Task 2
Find the average age of men in dataset

In [27]:
data_clean[data_clean["sex"] == "Male"]["age"].mean()

39.18400392541707

# Task 3
Get the percentage of people from Poland (native-country)

In [28]:
len(data_clean[data_clean["native-country"] == "Poland"]) * 100 / len(data_clean)

0.18566408063125786

# Task 4
Get the mean and standard deviation of the age for people who earn > 50K per year. After this, get it for those who earn <= 50K.

In [40]:
data_clean[data_clean["salary"] == ">50K"]["age"].mean()
data_clean[data_clean["salary"] == ">50K"]["age"].std()

data_clean[data_clean["salary"] == "<=50K"]["age"].mean()
data_clean[data_clean["salary"] == "<=50K"]["age"].std()

13.464631257161633

# Task 5
Check, if there are some people without higher education (education: Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters, Doctorate), but with > 50K salary

In [34]:
higher_edu = pd.Series([
    "Bachelors",
    "Prof-school",
    "Assoc-acdm",
    "Assoc-voc",
    "Masters",
    "Doctorate"
])

# Filter rows: NOT in higher_edu AND salary > 50K
result = data_clean[
    (~data_clean["education"].isin(higher_edu)) &
    (data_clean["salary"] == ">50K")
]

result

,Unnamed: 0,age,workclass,education,marital-status,occupation,relationship,race,sex,hours-per-week,native-country,salary,salary K$
7,7,52,Self-emp-not-inc,HS-grad,Married-civ-spouse,Exec-managerial,Husband,White,Male,45,United-States,>50K,307
10,10,37,Private,Some-college,Married-civ-spouse,Exec-managerial,Husband,Black,Male,80,United-States,>50K,116
55,55,43,Private,Some-college,Married-civ-spouse,Tech-support,Husband,White,Male,40,United-States,>50K,341
67,67,53,Private,HS-grad,Married-civ-spouse,Adm-clerical,Wife,White,Female,40,United-States,>50K,225
68,68,49,Self-emp-inc,Some-college,Married-civ-spouse,Exec-managerial,Husband,White,Male,50,United-States,>50K,194
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32462,32462,48,Self-emp-inc,HS-grad,Married-civ-spouse,Craft-repair,Husband,White,Male,50,United-States,>50K,343
32518,32518,57,Local-gov,HS-grad,Married-civ-spouse,Craft-repair,Husband,White,Male,40,United-States,>50K,116
32519,32519,46,Private,Some-college,Married-civ-spouse,Exec-managerial,Husband,White,Male,48,United-States,>50K,239
32557,32557,40,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,40,United-States,>50K,173
32560,32560,52,Self-emp-inc,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,40,United-States,>50K,243

# Task 6
Get the statistics of age for each type of education. Use `groupby` and `describe` for this.

In [31]:
data_clean.groupby("education")["age"].describe()

               count       mean        std   min   25%   50%   75%   max
education
10th           820.0  37.897561  16.225795  17.0  23.0  36.0  52.0  90.0
11th          1048.0  32.363550  15.089307  17.0  18.0  28.5  43.0  90.0
12th           377.0  32.013263  14.373710  17.0  19.0  28.0  41.0  79.0
1st-4th        151.0  44.622517  14.929051  19.0  33.0  44.0  56.0  81.0
5th-6th        288.0  41.649306  14.754622  17.0  28.0  41.0  53.0  82.0
7th-8th        557.0  47.631957  15.737479  17.0  34.0  49.0  60.0  90.0
9th            455.0  40.303297  15.335754  17.0  28.0  38.0  53.0  90.0
Assoc-acdm    1008.0  37.286706  10.509755  19.0  29.0  36.0  44.0  90.0
Assoc-voc     1307.0  38.246366  11.181253  19.0  30.0  37.0  45.0  84.0
Bachelors     5044.0  38.641554  11.577566  19.0  29.0  37.0  46.0  90.0
Doctorate      375.0  47.130667  11.471727  24.0  39.0  47.0  54.0  80.0
HS-grad       9840.0  38.640955  13.067730  17.0  28.0  37.0  48.0  90.0
Masters       1627.0  43.740012  10.735356  18.0  36.0  43.0  50.0  90.0
Preschool       45.0  41.288889  15.175672  19.0  30.0  40.0  53.0  75.0
Prof-school    542.0  44.249077  11.428098  25.0  36.0  43.0  50.0  90.0
Some-college  6678.0  36.135370  13.073528  17.0  25.0  35.0  45.0  90.0

# Task 7
Compare the married and non-married men salaries. Who earns more? (>50K or <=50K)
Married men are those, whom `marital-status` starts with "Married". Others are not.

In [32]:
men = data_clean[data_clean["sex"] == "Male"]
married_mask = men["marital-status"].str.startswith("Married")

married_men = men[married_mask]
non_married_men = men[~married_mask]

married_salary = married_men["salary"].value_counts()
non_married_salary = non_married_men["salary"].value_counts()

married_salary, non_married_salary

(salary
 <=50K    7052
 >50K     5723
 Name: count, dtype: int64,
 salary
 <=50K    6932
 >50K      673
 Name: count, dtype: int64)

# Task 8
Get the max hours per week some person works. How many people works the same amount of hours per week?

In [33]:
max_hours = data_clean["hours-per-week"].max()
count_max_hours = (data_clean["hours-per-week"] == max_hours).sum()

max_hours, count_max_hours

(99, 78)

# Task 9
Analyze the correlation between data in dataset. Understand connected fields in it and print highlight thier connection.

In [36]:
categorical_cols = data_clean.select_dtypes(include=['object']).columns

df_encoded = pd.get_dummies(data_clean, columns=categorical_cols, drop_first=True)

correlation_matrix = df_encoded.corr()

threshold = 0.7 

high_corr_pairs = correlation_matrix.unstack().sort_values(ascending=False)
high_corr_pairs = high_corr_pairs[high_corr_pairs.abs() >= threshold]
high_corr_pairs = high_corr_pairs[high_corr_pairs != 1.0]

high_corr_pairs.drop_duplicates()

salary_>50K  salary K$     0.853894
race_Black   race_White   -0.794808
dtype: float64